### ISSUE TITLE
Question about center_ratio and lane_ratio

### ISSUE THREAD

**Issue by SoulmateB** [czming/RONELD-Lane-Detection#3]
Hi, Thanks for providing the code. Would you tell me how to adjust the value of center_ratio and lane_ratio？for example, CULane datasets (1640x590)，pre-processing steps:
a. crop：1640x350 (from 240 to 590)
b. resize：976x208
so, the size of output map is 976x208(WxH)

**Comment by czming** [comment]
Hi, center_ratio and lane_ratio are both based on the width and height of the image, so e.g. center_ratio = 0.5 would use the center of the output map (976 * 0.5) as the line separating the right and left side of the image. Similarly for lane_ratio, but if you crop the output map then it would be a ratio of the cropped output map's height.
