### ISSUE TITLE
only one lane is predicted 

### ISSUE THREAD

**Issue by Sagexs** [czming/RONELD-Lane-Detection#5]
hi, 

I tried your test.py file. Only the left lane is displayed. The right one is empty. Also the left lane is jumping...

Am I doing something wrong?

Greedings

**Comment by czming** [comment]
Hi,

Do you see something like this? 

![image](https://user-images.githubusercontent.com/16664600/101000678-3297a700-3599-11eb-98b3-95ae3f229895.png)

I'm not really sure on what could be causing only the left lane to show, but the lane doesn't seem to be jumping on the short clip included with the repo, maybe you could upload the output that you are seeing? Thanks!

**Comment by Sagexs** [comment]
here are all images 

https://agcocorp-my.sharepoint.com/:f:/p/tobias_blume/El8kYFic7vhKr8LsS1uVoQQB-XsRTDvgCkwvIxVpCZuFfQ?e=nZbQvw

**Comment by czming** [comment]
Hi, thanks for sharing the images. I'm not really sure what could be causing that error, could you display the output_images[1] return value of the function using imshow, that should show the output binary map for the right lane which was used for IoU evaluation. It should look something like that for the right lane.

![image](https://user-images.githubusercontent.com/16664600/101108996-cfe1f200-3610-11eb-9f96-e6e07a63c68b.png)

**Comment by Sagexs** [comment]
it's empty. It seems like the Problem is caused by a windows version of one of the requierments. On my linux laptop it runs like it should.

Ich checked the pkg version in both systems, they are all the same... crazy

**Comment by czming** [comment]
Yeah that's really weird, cause I ran this on both Windows and Linux and it works. I'm going to close this issue for now
